/**
 * The 144-point inspection checkpoint index (Appendix A of the Master
 * Transfer Brief). This is universal across every institution — the same
 * 144 questions get asked of every school, only the answers differ — so it
 * lives in one place and both the seed script and the agent-facing API
 * import it from here.
 */

export type DomainConfig = {
  prefix: string;
  domain: string;
  criticalUpTo: number; // checkpoints 1..N are critical, rest are not
  titles: string[];
};

export const DOMAINS: DomainConfig[] = [
  {
    prefix: "ADM",
    domain: "Admissions",
    criticalUpTo: 8,
    titles: [
      "Application platform(s) and applicant type path identified",
      "Application opening date verified",
      "Priority / early / regular application deadlines verified",
      "Application fee and waiver process verified",
      "Transcript submission rules verified",
      "Test score policy and submission method verified",
      "Recommendation requirements verified",
      "Essay / supplement requirements identified without ingesting content",
      "Major / college-specific application requirements verified",
      "Portfolio / audition / special program requirements mapped",
      "Application status portal and post-submit monitoring path identified",
      "Admission decision notification channel / timing mapped",
    ],
  },
  {
    prefix: "ENR",
    domain: "Admission to Enrollment",
    criticalUpTo: 8,
    titles: [
      "Acceptance / intent-to-enroll action identified",
      "Enrollment deposit amount verified",
      "Enrollment deposit deadline verified",
      "Deposit waiver / exemption path verified",
      "Deposit refundability / reversibility verified",
      "Student account / NetID activation path mapped",
      "Admitted-student portal checklist mapped",
      "Final transcript requirement verified",
      "AP / IB / dual-credit transcript handling mapped",
      "Residency classification confirmation mapped",
      "Deferral / gap / change-of-term process mapped",
      "Decline / withdrawal process and downstream cleanup mapped",
    ],
  },
  {
    prefix: "AID",
    domain: "Financial Aid",
    criticalUpTo: 8,
    titles: [
      "FAFSA / TASFA applicability identified",
      "School code and filing instructions verified",
      "Priority aid deadline verified",
      "Verification / missing-document workflow mapped",
      "Financial-aid portal identified",
      "Award notification timing / channel mapped",
      "Award acceptance requirements mapped",
      "Loan acceptance / entrance counseling dependencies mapped",
      "Parent PLUS / alternative loan workflow mapped",
      "Satisfactory Academic Progress rules linked",
      "Special circumstance / aid appeal process mapped",
      "Disbursement timing and enrollment dependency mapped",
    ],
  },
  {
    prefix: "SCH",
    domain: "Scholarships and Funding",
    criticalUpTo: 0,
    titles: [
      "Automatic merit consideration rules identified",
      "Separate institutional scholarship application mapped",
      "Priority scholarship deadline verified",
      "Department / college scholarship path mapped",
      "Honors-linked scholarship requirements mapped",
      "Outside scholarship payment process mapped",
      "Scholarship stacking / displacement rules sourced",
      "Renewal GPA / credit-hour requirements mapped",
      "Renewal review timing mapped",
      "Scholarship acceptance requirements mapped",
      "Scholarship appeal / reinstatement process mapped",
      "External scholarship search / official resources linked",
    ],
  },
  {
    prefix: "BIL",
    domain: "Tuition Billing 529",
    criticalUpTo: 8,
    titles: [
      "Tuition and mandatory-fee schedule source identified",
      "Initial bill availability timing mapped",
      "Payment due date verified",
      "Payment-plan enrollment and fees mapped",
      "Authorized payer / proxy access process mapped",
      "Electronic payment methods and convenience fees mapped",
      "529 payment workflow mapped",
      "529 lead-time / posting guidance mapped",
      "Prepaid tuition plan workflow mapped where applicable",
      "Refund / eRefund / direct-deposit setup mapped",
      "Late-payment consequence / registration cancellation mapped",
      "Tax form / 1098-T access path mapped",
    ],
  },
  {
    prefix: "HOU",
    domain: "Housing and Dining",
    criticalUpTo: 8,
    titles: [
      "First-year residency requirement / exemption mapped",
      "Housing application opening date verified",
      "Housing application fee / prepayment verified",
      "Housing priority / room-selection cutoff verified",
      "Housing contract dependency on admission/deposit mapped",
      "Roommate matching / selection workflow mapped",
      "Room-selection process and timing mapped",
      "Housing cancellation / refund rules mapped",
      "Early move-in workflow and fees mapped",
      "Move-in appointment / check-in process mapped",
      "Meal-plan requirement / selection workflow mapped",
      "Mail / package / residence-hall logistics linked",
    ],
  },
  {
    prefix: "HLT",
    domain: "Health Compliance Access",
    criticalUpTo: 8,
    titles: [
      "Immunization requirements identified",
      "Immunization submission system mapped",
      "Health clearance deadline / registration block verified",
      "Health-history / medical form requirement mapped",
      "Student health insurance requirement / waiver mapped",
      "FERPA authorization / parent access process mapped",
      "Emergency contact requirement mapped",
      "Disability / accessibility accommodation path mapped",
      "Mandatory safety / conduct / Title IX training mapped",
      "Alcohol / substance education requirement mapped where applicable",
      "Identity / MFA / security setup mapped",
      "Compliance holds and resolution path mapped",
    ],
  },
  {
    prefix: "ACA",
    domain: "Orientation and Academics",
    criticalUpTo: 8,
    titles: [
      "Orientation requirement / eligibility mapped",
      "Orientation registration opening date verified",
      "Orientation session dates / format mapped",
      "Orientation fee / refund rules mapped",
      "Pre-orientation modules / checklist mapped",
      "Advising dependency mapped",
      "Placement testing requirements mapped",
      "Course registration timing / mechanism mapped",
      "Major / college onboarding requirements mapped",
      "Academic calendar / first class date linked",
      "Add / drop / census-date rules linked",
      "Academic support / tutoring onboarding resources linked",
    ],
  },
  {
    prefix: "LOG",
    domain: "Campus Logistics",
    criticalUpTo: 0,
    titles: [
      "Student ID / mobile credential setup mapped",
      "Parking permit eligibility / purchase timing mapped",
      "Campus shuttle / transit system linked",
      "Move-in traffic / unloading instructions linked",
      "Student email activation and official-communication policy mapped",
      "Primary student mobile app(s) identified",
      "Wi-Fi / device onboarding linked",
      "Printing / technology support resources linked",
      "Bookstore / course-material workflow linked",
      "Mailing address / package center process mapped",
      "Emergency alert enrollment mapped",
      "Campus map / building-navigation resource linked",
    ],
  },
  {
    prefix: "GRK",
    domain: "Greek and Student Life",
    criticalUpTo: 0,
    titles: [
      "Greek council structure and official source mapped",
      "Primary recruitment registration opening date verified",
      "Recruitment registration deadline verified",
      "Recruitment fee verified",
      "Eligibility / GPA requirements mapped",
      "Recruitment schedule / rounds mapped",
      "Early move-in implications / fees mapped",
      "Recommendation / reference-letter guidance mapped",
      "PNM resume / video / profile requirements mapped",
      "Conflict / accommodation process mapped",
      "Bid Day / post-recruitment transition mapped",
      "Non-Greek clubs / involvement portal linked",
    ],
  },
  {
    prefix: "FAM",
    domain: "Family and Campus Experience",
    criticalUpTo: 0,
    titles: [
      "Parent / family portal or program identified",
      "Family orientation registration mapped",
      "Authorized-user / proxy financial access mapped",
      "Family communication / newsletter opt-in mapped",
      "Move-in family logistics linked",
      "Parent / family weekend dates source mapped",
      "Athletics student ticket process linked",
      "Football / major-event guest-ticket guidance linked where applicable",
      "Campus visitor parking / event logistics linked",
      "Family emergency / student-support contacts mapped",
      "Break / holiday calendar linked",
      "Travel / airport / intercity transportation resources linked",
    ],
  },
  {
    prefix: "CAR",
    domain: "Career and Progression",
    criticalUpTo: 0,
    titles: [
      "Career center onboarding path linked",
      "Career platform (Handshake / equivalent) mapped",
      "Major / career exploration resources linked",
      "Resume / interview support mapped",
      "Internship search platform / process mapped",
      "Internship-for-credit rules linked",
      "Career fair calendar / registration mapped",
      "Co-op / experiential learning options mapped",
      "Research / undergraduate opportunity source linked",
      "Major milestone / progression requirements linkable",
      "Graduation application / degree-audit path mapped",
      "Alumni career access / transition resources linked",
    ],
  },
];

export type Checkpoint = { code: string; domain: string; title: string; critical: boolean };

export const ALL_CHECKPOINTS: Checkpoint[] = DOMAINS.flatMap((d) =>
  d.titles.map((title, i) => ({
    code: `${d.prefix}-${String(i + 1).padStart(2, "0")}`,
    domain: d.domain,
    title,
    critical: i + 1 <= d.criticalUpTo,
  }))
);
